version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    # Ensure your app logs go to stdout so Loki/Promtail can pick them up

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - './prometheus.yml:/etc/prometheus/prometheus.yml:ro'
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secret
    ports:
      - "3000:3000"

  # (Optional) Loki + Promtail for log aggregation:
  loki:
    image: grafana/loki:2.8.2
    container_name: loki
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    volumes:
      - ./loki-local-config.yaml:/etc/loki/local-config.yaml:ro
      - loki-data:/loki

  promtail:
    image: grafana/promtail:2.8.2
    container_name: promtail
    command: -config.file=/etc/promtail/config.yml
    volumes:
      - ./promtail/config.yml:/etc/promtail/config.yml:ro
      # Mount host log directories you want to scrape:
      - /var/log:/var/log:ro
      # Persist Promtail’s positions file so it remembers where it left off:
      - promtail-data:/promtail
    depends_on:
      - loki

volumes:
  loki-data:
  promtail-data:
