server:
  http_listen_port: 9080
  grpc_listen_port: 0       # disable gRPC; HTTP is enough for Loki push

positions:
  filename: /promtail/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/**/*.log   # adjust for the files you care about
